attr = {
    'callable': {'at': ['rows', 'columns'],
                 'iat': ['rows', 'columns'],
                 'iloc': ['rows', 'columns'],
                 'loc': ['rows', 'columns']},
    'attribute': ['T', 'axes', 'columns', 'dtypes', 'empty', 'ftypes', 'index', 'ndim', 'shape', 'size', 'style',
                  'timetuple', 'values']
}

method = {
    'abs': ['self'],
    'add': ['self', 'other', 'axis', 'level', 'fill_value'],
    'add_prefix': ['self', 'prefix'],
    'add_suffix': ['self', 'suffix'],
    'agg': ['self', 'func', 'axis'],
    'aggregate': ['self', 'func', 'axis'],
    'align': ['self',
              'other',
              'join',
              'axis',
              'level',
              'copy',
              'fill_value',
              'method',
              'limit',
              'fill_axis',
              'broadcast_axis'],
    'all': ['self', 'axis', 'bool_only', 'skipna', 'level'],
    'any': ['self', 'axis', 'bool_only', 'skipna', 'level'],
    'append': ['self', 'other', 'ignore_index', 'verify_integrity', 'sort'],
    'apply': ['self',
              'func',
              'axis',
              'broadcast',
              'raw',
              'reduce',
              'result_type',
              'args'],
    'applymap': ['self', 'func'],
    'as_matrix': ['self', 'columns'],
    'asfreq': ['self', 'freq', 'method', 'how', 'normalize', 'fill_value'],
    'asof': ['self', 'where', 'subset'],
    'assign': ['self'],
    'astype': ['self', 'dtype', 'copy', 'errors'],
    'at_time': ['self', 'time', 'asof', 'axis'],
    'between_time': ['self',
                     'start_time',
                     'end_time',
                     'include_start',
                     'include_end',
                     'axis'],
    'bfill': ['self', 'axis', 'inplace', 'limit', 'downcast'],
    'bool': ['self'],
    'boxplot': ['self',
                'column',
                'by',
                'ax',
                'fontsize',
                'rot',
                'grid',
                'figsize',
                'layout',
                'return_type'],
    'clip': ['self', 'lower', 'upper', 'axis', 'inplace'],
    'clip_lower': ['self', 'threshold', 'axis', 'inplace'],
    'clip_upper': ['self', 'threshold', 'axis', 'inplace'],
    'combine': ['self', 'other', 'func', 'fill_value', 'overwrite'],
    'combine_first': ['self', 'other'],
    'compound': ['self', 'axis', 'skipna', 'level'],
    'copy': ['self', 'deep'],
    'corr': ['self', 'method', 'min_periods'],
    'corrwith': ['self', 'other', 'axis', 'drop', 'method'],
    'count': ['self', 'axis', 'level', 'numeric_only'],
    'cov': ['self', 'min_periods'],
    'cummax': ['self', 'axis', 'skipna'],
    'cummin': ['self', 'axis', 'skipna'],
    'cumprod': ['self', 'axis', 'skipna'],
    'cumsum': ['self', 'axis', 'skipna'],
    'describe': ['self', 'percentiles', 'include', 'exclude'],
    'diff': ['self', 'periods', 'axis'],
    'div': ['self', 'other', 'axis', 'level', 'fill_value'],
    'divide': ['self', 'other', 'axis', 'level', 'fill_value'],
    'dot': ['self', 'other'],
    'drop': ['self',
             'labels',
             'axis',
             'index',
             'columns',
             'level',
             'inplace',
             'errors'],
    'drop_duplicates': ['self', 'subset', 'keep', 'inplace'],
    'droplevel': ['self', 'level', 'axis'],
    'dropna': ['self', 'axis', 'how', 'thresh', 'subset', 'inplace'],
    'duplicated': ['self', 'subset', 'keep'],
    'eq': ['self', 'other', 'axis', 'level'],
    'equals': ['self', 'other'],
    'eval': ['self', 'expr', 'inplace'],
    'ewm': ['self',
            'com',
            'span',
            'halflife',
            'alpha',
            'min_periods',
            'adjust',
            'ignore_na',
            'axis'],
    'expanding': ['self', 'min_periods', 'center', 'axis'],
    'ffill': ['self', 'axis', 'inplace', 'limit', 'downcast'],
    'fillna': ['self', 'value', 'method', 'axis', 'inplace', 'limit', 'downcast'],
    'filter': ['self', 'items', 'like', 'regex', 'axis'],
    'first': ['self', 'offset'],
    'first_valid_index': ['self'],
    'floordiv': ['self', 'other', 'axis', 'level', 'fill_value'],
    'ge': ['self', 'other', 'axis', 'level'],
    'get': ['self', 'key', 'default'],
    'get_dtype_counts': ['self'],
    'get_ftype_counts': ['self'],
    'get_values': ['self'],
    'groupby': ['self',
                'by',
                'axis',
                'level',
                'as_index',
                'sort',
                'group_keys',
                'squeeze',
                'observed'],
    'gt': ['self', 'other', 'axis', 'level'],
    'head': ['self', 'n'],
    'hist': ['data',
             'column',
             'by',
             'grid',
             'xlabelsize',
             'xrot',
             'ylabelsize',
             'yrot',
             'ax',
             'sharex',
             'sharey',
             'figsize',
             'layout',
             'bins'],
    'idxmax': ['self', 'axis', 'skipna'],
    'idxmin': ['self', 'axis', 'skipna'],
    'infer_objects': ['self'],
    'info': ['self', 'verbose', 'buf', 'max_cols', 'memory_usage', 'null_counts'],
    'insert': ['self', 'loc', 'column', 'value', 'allow_duplicates'],
    'interpolate': ['self',
                    'method',
                    'axis',
                    'limit',
                    'inplace',
                    'limit_direction',
                    'limit_area',
                    'downcast'],
    'isin': ['self', 'values'],
    'isna': ['self'],
    'isnull': ['self'],
    'items': ['self'],
    'iteritems': ['self'],
    'iterrows': ['self'],
    'itertuples': ['self', 'index', 'name'],
    'join': ['self', 'other', 'on', 'how', 'lsuffix', 'rsuffix', 'sort'],
    'keys': ['self'],
    'kurt': ['self', 'axis', 'skipna', 'level', 'numeric_only'],
    'kurtosis': ['self', 'axis', 'skipna', 'level', 'numeric_only'],
    'last': ['self', 'offset'],
    'last_valid_index': ['self'],
    'le': ['self', 'other', 'axis', 'level'],
    'lookup': ['self', 'row_labels', 'col_labels'],
    'lt': ['self', 'other', 'axis', 'level'],
    'mad': ['self', 'axis', 'skipna', 'level'],
    'mask': ['self',
             'cond',
             'other',
             'inplace',
             'axis',
             'level',
             'errors',
             'try_cast',
             'raise_on_error'],
    'max': ['self', 'axis', 'skipna', 'level', 'numeric_only'],
    'mean': ['self', 'axis', 'skipna', 'level', 'numeric_only'],
    'median': ['self', 'axis', 'skipna', 'level', 'numeric_only'],
    'melt': ['self',
             'id_vars',
             'value_vars',
             'var_name',
             'value_name',
             'col_level'],
    'memory_usage': ['self', 'index', 'deep'],
    'merge': ['self',
              'right',
              'how',
              'on',
              'left_on',
              'right_on',
              'left_index',
              'right_index',
              'sort',
              'suffixes',
              'copy',
              'indicator',
              'validate'],
    'min': ['self', 'axis', 'skipna', 'level', 'numeric_only'],
    'mod': ['self', 'other', 'axis', 'level', 'fill_value'],
    'mode': ['self', 'axis', 'numeric_only', 'dropna'],
    'mul': ['self', 'other', 'axis', 'level', 'fill_value'],
    'multiply': ['self', 'other', 'axis', 'level', 'fill_value'],
    'ne': ['self', 'other', 'axis', 'level'],
    'nlargest': ['self', 'n', 'columns', 'keep'],
    'notna': ['self'],
    'notnull': ['self'],
    'nsmallest': ['self', 'n', 'columns', 'keep'],
    'nunique': ['self', 'axis', 'dropna'],
    'pct_change': ['self', 'periods', 'fill_method', 'limit', 'freq'],
    'pipe': ['self', 'func'],
    'pivot': ['self', 'index', 'columns', 'values'],
    'pivot_table': ['self',
                    'values',
                    'index',
                    'columns',
                    'aggfunc',
                    'fill_value',
                    'margins',
                    'dropna',
                    'margins_name'],
    'pop': ['self', 'item'],
    'pow': ['self', 'other', 'axis', 'level', 'fill_value'],
    'prod': ['self', 'axis', 'skipna', 'level', 'numeric_only', 'min_count'],
    'product': ['self', 'axis', 'skipna', 'level', 'numeric_only', 'min_count'],
    'quantile': ['self', 'q', 'axis', 'numeric_only', 'interpolation'],
    'query': ['self', 'expr', 'inplace'],
    'radd': ['self', 'other', 'axis', 'level', 'fill_value'],
    'rank': ['self',
             'axis',
             'method',
             'numeric_only',
             'na_option',
             'ascending',
             'pct'],
    'rdiv': ['self', 'other', 'axis', 'level', 'fill_value'],
    'reindex': [],
    'reindex_axis': ['self',
                     'labels',
                     'axis',
                     'method',
                     'level',
                     'copy',
                     'limit',
                     'fill_value'],
    'reindex_like': ['self', 'other', 'method', 'copy', 'limit', 'tolerance'],
    'rename': [],
    'rename_axis': [],
    'reorder_levels': ['self', 'order', 'axis'],
    'replace': ['self',
                'to_replace',
                'value',
                'inplace',
                'limit',
                'regex',
                'method'],
    'resample': ['self',
                 'rule',
                 'how',
                 'axis',
                 'fill_method',
                 'closed',
                 'label',
                 'convention',
                 'kind',
                 'loffset',
                 'limit',
                 'base',
                 'on',
                 'level'],
    'reset_index': ['self', 'level', 'drop', 'inplace', 'col_level', 'col_fill'],
    'rfloordiv': ['self', 'other', 'axis', 'level', 'fill_value'],
    'rmod': ['self', 'other', 'axis', 'level', 'fill_value'],
    'rmul': ['self', 'other', 'axis', 'level', 'fill_value'],
    'rolling': ['self',
                'window',
                'min_periods',
                'center',
                'win_type',
                'on',
                'axis',
                'closed'],
    'round': ['self', 'decimals'],
    'rpow': ['self', 'other', 'axis', 'level', 'fill_value'],
    'rsub': ['self', 'other', 'axis', 'level', 'fill_value'],
    'rtruediv': ['self', 'other', 'axis', 'level', 'fill_value'],
    'sample': ['self', 'n', 'frac', 'replace', 'weights', 'random_state', 'axis'],
    'select': ['self', 'crit', 'axis'],
    'select_dtypes': ['self', 'include', 'exclude'],
    'sem': ['self', 'axis', 'skipna', 'level', 'ddof', 'numeric_only'],
    'set_axis': ['self', 'labels', 'axis', 'inplace'],
    'set_index': ['self',
                  'keys',
                  'drop',
                  'append',
                  'inplace',
                  'verify_integrity'],
    'shift': ['self', 'periods', 'freq', 'axis', 'fill_value'],
    'skew': ['self', 'axis', 'skipna', 'level', 'numeric_only'],
    'slice_shift': ['self', 'periods', 'axis'],
    'sort_index': ['self',
                   'axis',
                   'level',
                   'ascending',
                   'inplace',
                   'kind',
                   'na_position',
                   'sort_remaining',
                   'by'],
    'sort_values': ['self',
                    'by',
                    'axis',
                    'ascending',
                    'inplace',
                    'kind',
                    'na_position'],
    'squeeze': ['self', 'axis'],
    'stack': ['self', 'level', 'dropna'],
    'std': ['self', 'axis', 'skipna', 'level', 'ddof', 'numeric_only'],
    'sub': ['self', 'other', 'axis', 'level', 'fill_value'],
    'subtract': ['self', 'other', 'axis', 'level', 'fill_value'],
    'sum': ['self', 'axis', 'skipna', 'level', 'numeric_only', 'min_count'],
    'swapaxes': ['self', 'axis1', 'axis2', 'copy'],
    'swaplevel': ['self', 'i', 'j', 'axis'],
    'tail': ['self', 'n'],
    'take': ['self', 'indices', 'axis', 'convert', 'is_copy'],
    'transform': ['self', 'func', 'axis'],
    'transpose': ['self'],
    'truediv': ['self', 'other', 'axis', 'level', 'fill_value'],
    'truncate': ['self', 'before', 'after', 'axis', 'copy'],
    'tshift': ['self', 'periods', 'freq', 'axis'],
    'tz_convert': ['self', 'tz', 'axis', 'level', 'copy'],
    'tz_localize': ['self',
                    'tz',
                    'axis',
                    'level',
                    'copy',
                    'ambiguous',
                    'nonexistent'],
    'unstack': ['self', 'level', 'fill_value'],
    'update': [],
    'var': ['self', 'axis', 'skipna', 'level', 'ddof', 'numeric_only'],
    'where': ['self',
              'cond',
              'other',
              'inplace',
              'axis',
              'level',
              'errors',
              'try_cast',
              'raise_on_error'],
    'xs': ['self', 'key', 'axis', 'level', 'drop_level']}

